In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
arr1=np.array([[10,20,30,40],[50,60,70,80]])

In [4]:
arr[0:3]

array([10, 20, 30])

In [5]:
arr1[0:2,0:3]

array([[10, 20, 30],
       [50, 60, 70]])

In [6]:
arr1[1,2:]

array([70, 80])

In [7]:
np.size(arr1)

8

In [8]:
np.shape(arr1)

(2, 4)

In [9]:
np.ndim(arr)

1

In [10]:
arr.dtype

dtype('int32')

In [11]:
a=np.array([10,20,30])

In [12]:
a.shape

(3,)

In [13]:
a.size

3

In [14]:
len(a)

3

In [15]:
a.ndim

1

In [16]:
a.dtype

dtype('int32')

In [17]:
a.astype(float)

array([10., 20., 30.])

In [18]:
a

array([10, 20, 30])

In [19]:
b=np.array([40,50,60])

In [20]:
b

array([40, 50, 60])

In [21]:
np.subtract(a,b)

array([-30, -30, -30])

In [22]:
np.add(a,b)

array([50, 70, 90])

In [23]:
np.multiply(a,b)

array([ 400, 1000, 1800])

In [24]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [25]:
np.exp(b)

array([2.35385267e+17, 5.18470553e+21, 1.14200739e+26])

In [26]:
np.sqrt(b)

array([6.32455532, 7.07106781, 7.74596669])

In [27]:
a=np.array([5,3])
b=np.array([2,3])
np.power(a,b)

array([25, 27])

In [28]:
ar1=np.array([[10, 20],[30,90]])

In [29]:
ar2=np.array([[40, 50],[70, 60]])

In [30]:
np.concatenate([ar1,ar2])

array([[10, 20],
       [30, 90],
       [40, 50],
       [70, 60]])

In [31]:
np.concatenate([ar1,ar2],axis=1)

array([[10, 20, 40, 50],
       [30, 90, 70, 60]])

In [32]:
np.hstack([ar1,ar2])

array([[10, 20, 40, 50],
       [30, 90, 70, 60]])

In [33]:
np.vstack([ar1,ar2])

array([[10, 20],
       [30, 90],
       [40, 50],
       [70, 60]])

In [34]:
ar3=np.array([20,40,60,80])

In [35]:
np.array_split(ar3,3)

[array([20, 40]), array([60]), array([80])]

In [36]:
h=np.array([4,5,6,7,15])
g=np.array([8,9,10,11])
np.append(h,g)

array([ 4,  5,  6,  7, 15,  8,  9, 10, 11])

In [37]:
np.insert(ar3,1,6)

array([20,  6, 40, 60, 80])

In [38]:
np.delete(ar3,1)

array([20, 60, 80])

In [48]:
c=np.array([[20,40],[50,60]])

In [58]:
np.append(c,90)

array([20, 40, 50, 60, 90])

In [64]:
d=np.insert(c,1,50)

In [68]:
np.delete(d,1)

array([20, 40, 50, 60])

In [72]:
np.delete(c,1,axis=1)

array([[20],
       [50]])

In [89]:
T=np.array([1,2,8,3,4,5,6])

In [91]:
np.sort(T)

array([1, 2, 3, 4, 5, 6, 8])

In [101]:
S=np.where(T%2==0)

In [114]:
S#-->it produce index number

(array([1, 2, 4, 6], dtype=int64),)

In [116]:
Tania=np.array([20,40,60,70])

In [118]:
np.sum(Tania)

190

In [120]:
np.min(Tania)

20

In [122]:
np.max(Tania)

70

In [124]:
np.size(Tania)

4

In [126]:
np.mean(Tania)

47.5

In [128]:
np.cumsum(Tania)

array([ 20,  60, 120, 190])

In [130]:
np.cumprod(Tania)

array([     20,     800,   48000, 3360000])

In [132]:
L=[100,150,199,200,250,130]
O=[10,50,30,40,30,10]

In [134]:
price=np.array(L)

In [138]:
Quantity=np.array(O)

In [140]:
price,Quantity

(array([100, 150, 199, 200, 250, 130]), array([10, 50, 30, 40, 30, 10]))

In [152]:
v=np.cumprod([price,Quantity],axis=0)

In [156]:
v

array([[ 100,  150,  199,  200,  250,  130],
       [1000, 7500, 5970, 8000, 7500, 1300]])

In [154]:
v[1].sum()

31270